all:
	make -f Makefile_LIB clean
	make -f Makefile_LIB
	make -f Makefile_db clean
	make -f Makefile_db
	make -f Makefile_sdb clean
	make -f Makefile_sdb
db:
	make -f Makefile_db clean
	make -f Makefile_db
sdb:
	make -f Makefile_sdb clean
	make -f Makefile_sdb
clean:
	make -f Makefile_LIB clean
	make -f Makefile_db clean
	make -f Makefile_sdb clean

