all:
	make -f Makefile_db clean
	make -f Makefile_db
	make -f Makefile_st clean
	make -f Makefile_st
db:
	make -f Makefile_db clean
	make -f Makefile_db
st:
	make -f Makefile_st clean
	make -f Makefile_st
clean:
	make -f Makefile_db clean
	make -f Makefile_st clean
