#ifndef _PROTOCOL_H_
#define _PROTOCOL_H_

#include "DataStruct.h"

const BYTE GROUPCODE						= 0xD0;
const BYTE GROUPCODE_DB_LOGIN				= 0xD1;
const BYTE GROUPCODE_DB_D					= 0xD2;
const BYTE GROUPCODE_DB_STATUS				= 0xD3;
const BYTE GROUPCODE_DB_NOTIFICATION		= 0xD4;
const BYTE GROUPCODE_D_DEVICE				= 0xD5;
const BYTE GROUPCODE_D_CLIENT				= 0xD6;
const BYTE GROUPCODE_D_NB					= 0xD7;
const BYTE GROUPCODE_D_LOGIN				= 0xD8;
const BYTE GROUPCODE_D_STATUS				= 0xD9;
const BYTE GROUPCODE_LOGIN_CLIENT			= 0xDA;
const BYTE GROUPCODE_NOTIFICATION_D			= 0xDB;
const BYTE GROUPCODE_NOTIFICATION_LOGIN		= 0xDC;
const BYTE GROUPCODE_NOTIFICATION_STATUS	= 0xDD;
const BYTE GROUPCODE_CGI					= 0xDE;
const BYTE GROUPCODE_P2P					= 0xDF;
const BYTE GROUPCODE_DB_NB					= 0xE1;
const BYTE GROUPCODE_SDB_SB					= 0xE2;
const BYTE GROUPCODE_D_SB					= 0xE3;

const WORD CMD_GET_SERVER_INFO				= 0x0001;
const WORD CMD_GET_SERVER_INFO_REP			= 0x0002;
const WORD CMD_QUERY_USER					= 0x0003;
const WORD CMD_QUERY_USER_REP				= 0x0004;
const WORD CMD_SET_SECRET					= 0x0005;
const WORD CMD_SET_SECRET_REP				= 0x0006;
const WORD CMD_PIECE_OF_SERIALNO			= 0x0007;
const WORD CMD_DSERVER_CONFIGUREINDEX		= 0x0008;
const WORD CMD_USER_CONFIGUREINDEX			= 0x0009;
const WORD CMD_DEVICE_CONFIGUREINDEX		= 0x000A;
const WORD CMD_GET_USER_INFO				= 0x000B;
const WORD CMD_GET_USER_INFO_REP			= 0x000C;
const WORD CMD_GET_USERDEVICE_INFO			= 0x000D;
const WORD CMD_GET_USERDEVICE_INFO_REP		= 0x000E;
const WORD CMD_GET_USERGROUP_INFO			= 0x000F;
const WORD CMD_GET_USERGROUP_INFO_REP		= 0x0010;
const WORD CMD_GET_DEVICE_INFO				= 0x0011;
const WORD CMD_GET_DEVICE_INFO_REP			= 0x0012;
const WORD CMD_GET_DEVICEUSER_INFO			= 0x0013;
const WORD CMD_GET_DEVICEUSER_INFO_REP		= 0x0014;
const WORD CMD_GET_DEVICEPUSH_INFO			= 0x0015;
const WORD CMD_GET_DEVICEPUSH_INFO_REP		= 0x0016;
const WORD CMD_ADD_DEVICE					= 0x0017;
const WORD CMD_ADD_DEVICE_REP				= 0x0018;
const WORD CMD_ADD_DEL_PUSH_INFO			= 0x0019;
const WORD CMD_ADD_DEL_PUSH_INFO_REP		= 0x001A;
const WORD CMD_REGISTER						= 0x001B;
const WORD CMD_REGISTER_REP					= 0x001C;
const WORD CMD_REPORT_NETWORK				= 0x001D;
const WORD CMD_REPORT_DEVICE_STATUS			= 0x001E;
const WORD CMD_REPORT_DEVICE_STATUS_REP		= 0x001F;
const WORD CMD_CLIENT_AUTH					= 0x0020;
const WORD CMD_AUTH_REP						= 0x0021;
const WORD CMD_ADD_TMP_USER					= 0x0022;
const WORD CMD_ADD_TMP_USER_REP				= 0x0023;
const WORD CMD_REPORT_USER_STATUS			= 0x0024;
const WORD CMD_GET_DEVICE_STATUS			= 0x0025;
const WORD CMD_GET_DEVICE_STATUS_REP		= 0x0026;
const WORD CMD_TRANS_CLIENTINFO				= 0x0027;
const WORD CMD_TRANS_SERVERINFO				= 0x0028;
const WORD CMD_GET_REGISTER_INFO			= 0x0029;
const WORD CMD_GET_REGISTER_INFO_REP		= 0x002A;
const WORD CMD_SMS							= 0x002B;
const WORD CMD_SMS_REP						= 0x002C;
const WORD CMD_PUSH							= 0x002D;
const WORD CMD_PUSH_REP						= 0x002E;
const WORD CMD_SERVER_AUTH					= 0x002F;
const WORD CMD_GET_CHALLENGE				= 0x0030;
const WORD CMD_GET_CHALLENGE_REP			= 0x0031;
const WORD CMD_ERROR						= 0x0032;
const WORD CMD_PIECE_OF_SERIALNO_REP		= 0x0033;
const WORD CMD_DSERVER_CONFIGUREINDEX_REP	= 0x0034;
const WORD CMD_USER_CONFIGUREINDEX_REP		= 0x0035;
const WORD CMD_DEVICE_CONFIGUREINDEX_REP	= 0x0036;
const WORD CMD_SET_DEVICE_NAME				= 0x0037;
const WORD CMD_SET_DEVICE_NAME_REP			= 0x0038;

const WORD CMD_P2P_FIRST_CMD				= 0x0039;

const WORD CMD_DEL_DEVICE					= 0x003A;
const WORD CMD_DEL_DEVICE_REP				= 0x003B;
const WORD CMD_AUTHORIZE					= 0x003C;
const WORD CMD_AUTHORIZE_REP				= 0x003D;

// 房号信息同步命令
const WORD CMD_GET_DEVICE_ROOM_SUM			= 0x003E;
const WORD CMD_GET_DEVICE_ROOM_SUM_REP		= 0x003F;
const WORD CMD_GET_DEVICE_ROOM_SUM_REP_ACK	= 0x0040;
const WORD CMD_GET_DEVICE_ROOMINFO			= 0x0041;
const WORD CMD_GET_DEVICE_ROOMUSER_REP		= 0x0042;
const WORD CMD_GET_DEVICE_ROOMPUSH_REP		= 0x0043;
const WORD CMD_GET_DEVICE_ROOMCARD_REP		= 0x0044;
const WORD CMD_GET_DEVICE_ROOMOTHER_REP		= 0x0045;
const WORD CMD_GET_DEVICE_ROOMINFO_REP_ACK	= 0x0046;
const WORD CMD_DELETE_DEVICE_ROOM			= 0x0047;

// 数据库服务器通知命令
const WORD CMD_UPDATE_DEVICE_ROOMINFO		= 0x0048;
const WORD CMD_UPDATE_DEVICE				= 0x0049;
const WORD CMD_CLEAR_ROOMS					= 0x004A;

// 外放注册服务器获取许可信息
const WORD CMD_GET_DSERVER_INFO				= 0x004B;
const WORD CMD_GET_DSERVER_INFO_REP			= 0x004C;

// 支持多个第三方推送设置
const WORD CMD_ADD_DEL_PUSH_INFO_EX			= 0x004D;
const WORD CMD_ADD_DEL_PUSH_INFO_EX_REP		= 0x004E;

// 客户端sdk透传协议
const WORD CMD_SDK_TUNNEL					= 0x004F;
const WORD CMD_SDK_TUNNEL_REP				= 0x0050;

// 云存储获取上传凭证/下载外链
const WORD CMD_GET_UPLOAD_TOKEN				= 0x0051;
const WORD CMD_GET_UPLOAD_TOKEN_REP			= 0x0052;
const WORD CMD_GET_DOWNLOAD_URLS			= 0x0053;
const WORD CMD_GET_DOWNLOAD_URLS_REP		= 0x0054;
const WORD CMD_GET_STORAGEACCOUNT			= 0x0055;
const WORD CMD_GET_STORAGEACCOUNT_REP		= 0x0056;
const WORD CMD_GET_STORAGEKEYS				= 0x0057;
const WORD CMD_GET_STORAGEKEYS_REP			= 0x0058;
const WORD CMD_REPORT_UPLOAD_RESULT			= 0x0059;


const WORD CMD_GET_USERROOM_INFO			= 0x005A;
const WORD CMD_GET_USERROOM_INFO_REP		= 0x005B;

const WORD CMD_AUTHORIZE2					= 0x005C;
const WORD CMD_AUTHORIZE2_REP				= 0x005D;

const WORD CMD_UPDATE_DEVICE_EX				= 0x005E;
const WORD CMD_UPDATE_DEVICE_EX_REP			= 0x005F;

const WORD CMD_GET_DEVICE_CFG				= 0x0060;
const WORD CMD_GET_DEVICE_CFG_REP			= 0x0061;

const WORD CMD_REPORT_UNLOCKLOG				= 0x0062;//用不到了。

const WORD CMD_PUSH_SWITCH					= 0x0063;
const WORD CMD_PUSH_SWITCH_REP				= 0x0064;
//const WORD CMD_GET_DEVICE_ROOM_PUSHSWITCH_REP	= 0x0065;
const WORD CMD_GET_DEVICE_ROOMINDOOR_REP	= 0x0065;

//发送截至日期协议
const WORD CMD_DEV_DEADLINE					= 0x0066;
const WORD CMD_GET_DEVICE_DEADLINE_REP		= 0x0072;

//设备获取平台时间
const WORD DD_CMD_GET_SERVERTIME			= 0x0067;
const WORD DD_CMD_GET_SERVERTIME_REP		= 0x0068;

//室内机获取绑定设备列表和在线离线状态
const WORD CMD_GET_LIST_DEV_STAT_REP		= 0x0069;

//通知设备更新广告
const WORD CMD_GET_ADVERT_INFO				= 0x006A;
const WORD CMD_GET_ADVERT_INFO_REP			= 0x006B;

//主动通知(内部使用)
const WORD CMD_NOTICE_INFO					= 0x006C;
const WORD CMD_ADVERT_INFO					= 0x006D;

//开门记录
const WORD DD_PUSH_UNLOCK_RECORD		= 0x0073;
const WORD DD_PUSH_UNLOCK_RECORD_REP	= 0x0074;

//更新物業公告
const WORD DD_UPDATE_BULLETIN			= 0x0075;
const WORD DD_UPDATE_BULLETIN_REP		= 0x0076;

//访客留影
const WORD CMD_GET_DOWNLOAD_URLS2		= 0x0077;
const WORD CMD_GET_DOWNLOAD_URLS_REP2	= 0x0078;

const WORD CMD_GET_STORAGEKEYS2			= 0x0079;
const WORD CMD_GET_STORAGEKEYS_REP2		= 0x0080;

//门口机离线通知室内机
const WORD CMD_GET_DEV_BIND_IDNOOR		= 0x007B;
const WORD CMD_GET_DEV_BIND_IDNOOR_REP	= 0x007C;

//获取室内机列表
const WORD CMD_GET_INDOOR_INFO			= 0x007D;
//特殊人群
const WORD CMD_UPDATE_SPECIALCROWD = 0x007E;

//远程设备升级
const WORD DD_UPDATE_FIRMWARE_REQUEST   = 0x0081;
//删除在线设备
const WORD DD_DELETE_DEVICE_ONLINE		= 0x0082;

//室内机
const WORD CMD_INDOOR_BIND_DEVICE		= 0x0083;
const WORD CMD_INDOOR_BIND_DEVICE_REP	= 0x0084;

//获取室内机绑定门口机列表
const WORD CMD_GET_BIND_DEV_STATE		= 0x0085;
const WORD CMD_GET_BIND_DEV_STATE_REP	= 0x0086;

//门口机呼叫室内机
const WORD CMD_CALL_INDOOR_DEV			= 0x0087;
const WORD CMD_CALL_INDOOR_DEV_REP		= 0x0088;

//通知门口机更新访客配置
const WORD CMD_UPDATE_VISITORCFG			=	0x0089;
const WORD CMD_UPDATE_VISITORCFG_REP	=	0x0090;

//上传报警状态
const WORD CMD_REPORT_ALARMSTATUS		= 0x0091;

const WORD CMD_REPORT_PROGRESS				= 0x0092;
//通过AdID更新广告
const WORD CMD_GET_ADVERTURLS				= 0x0093;
const WORD CMD_GET_ADVERTURLS_REP		= 0x0094;

//
const WORD CMD_GET_DEVICE_DEADLINE		= 0x0095;

struct PacketHeader_t {
	unsigned char   groupcode;								// 
	unsigned short  commandid;								// 
	unsigned char   reserved0;								// 0		
	unsigned short  version;								// 
	unsigned short  reserved1;								// 0
	unsigned long   sourceid;								// 
	unsigned long   destinationid;							// 
	unsigned long   commandflag;							// 
	unsigned short  totalsegment;							// N >= 1
	unsigned short  subsegment;								// 1....N
	unsigned short  segmentflag;							// 
	unsigned short  reserved2;								// 0
	unsigned long   reserved3;								// 0

	unsigned short  error;
	unsigned char	payloadversion;
};
const int PACKET_HEADER_SIZE = 44;

#endif //_PROTOCOL_H_
