all:
	make -f Makefile_d clean
	make -f Makefile_d
	make -f Makefile_login clean
	make -f Makefile_login
	make -f Makefile_status clean
	make -f Makefile_status
	make -f Makefile_notify clean
	make -f Makefile_notify
	make -f Makefile_relay clean
	make -f Makefile_relay
	make -f Makefile_storage_business clean
	make -f Makefile_storage_business
d:
	make -f Makefile_d clean
	make -f Makefile_d
login:
	make -f Makefile_login clean
	make -f Makefile_login
status:
	make -f Makefile_status clean
	make -f Makefile_status
notify:
	make -f Makefile_notify clean
	make -f Makefile_notify
relay:
	make -f Makefile_relay clean
	make -f Makefile_relay
sb:
	make -f Makefile_storage_business clean
	make -f Makefile_storage_business
clean:
	make -f Makefile_d clean
	make -f Makefile_login clean
	make -f Makefile_status clean
	make -f Makefile_notify clean
	make -f Makefile_relay clean
	make -f Makefile_storage_business clean
